# Workflow name
name: 'Chromatic Deployment'

on:
  pull_request:
    branches:
      - develop
    paths:
      - frontend/**

defaults:
  run:
    working-directory: frontend

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install dependencies and build
        run: npm install
      - name: publish to chromatic
        uses: chromaui/action@latest
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/ko/deploy/ to obtain it
          workingDir: ./frontend
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          exitZeroOnChanges: true
